# pubspec.yaml

name: seattle_info_mobile
description: A new Flutter project for Seattle Info.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2

  # Networking
  http: ^1.1.0 # Or dio: ^5.3.3

  # State Management (Choose one or combine)
  flutter_riverpod: ^2.4.5 # Example for Riverpod
  # or
  # flutter_bloc: ^8.1.3      # Example for BLoC/Cubit
  # equatable: ^2.0.5         # Often used with BLoC

  # Navigation (Choose one or use Flutter's built-in)
  go_router: ^15.1.2 # Example for GoRouter
  # or
  # auto_route: ^7.8.4

  # Dependency Injection (if not using Riverpod's capabilities)
  # get_it: ^7.6.4
  # injectable: ^2.3.2 # Code generator for GetIt

  # JSON Serialization (if not using manual conversion or if models are complex)
  # json_annotation: ^4.8.1 # Usually used with build_runner

  # Local Storage
  shared_preferences: ^2.2.2

  # Utility
  intl: ^0.20.2 # For date/number formatting
  # logger: ^2.0.2+1 # Or another logging package like `logging`

  # For .env file loading (optional, Flutter has other ways for config)
  # flutter_dotenv: ^5.1.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # For code generation (if using json_serializable, injectable, auto_route_generator, etc.)
  # build_runner: ^2.4.6
  # json_serializable: ^6.7.1
  # injectable_generator: ^2.4.1
  # auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - .env # If using flutter_dotenv