// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2YM_uP8u8D9BiWVQY8k7xq-7pqj6224k',
    appId: '1:1060028705881:web:a72b2ce8a16305edeed548',
    messagingSenderId: '1060028705881',
    projectId: 'seattle-info',
    authDomain: 'seattle-info.firebaseapp.com',
    storageBucket: 'seattle-info.firebasestorage.app',
    measurementId: 'G-SFWZSN7BQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnxFPjx7KPH_6csXtTnzzTsCvp8joBaAQ',
    appId: '1:1060028705881:android:7cc8913806cb94e5eed548',
    messagingSenderId: '1060028705881',
    projectId: 'seattle-info',
    storageBucket: 'seattle-info.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIP4ItxYdtkhcnTKEBRFQhwEj23NNyJiU',
    appId: '1:1060028705881:ios:8c1460abbec6af18eed548',
    messagingSenderId: '1060028705881',
    projectId: 'seattle-info',
    storageBucket: 'seattle-info.firebasestorage.app',
    androidClientId: '1060028705881-da24459qmsr2fi11201ga17npst0sach.apps.googleusercontent.com',
    iosClientId: '1060028705881-p0c1aqfh4auu814s95acoopeb30ans6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.seattleInfoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIP4ItxYdtkhcnTKEBRFQhwEj23NNyJiU',
    appId: '1:1060028705881:ios:8c1460abbec6af18eed548',
    messagingSenderId: '1060028705881',
    projectId: 'seattle-info',
    storageBucket: 'seattle-info.firebasestorage.app',
    androidClientId: '1060028705881-da24459qmsr2fi11201ga17npst0sach.apps.googleusercontent.com',
    iosClientId: '1060028705881-p0c1aqfh4auu814s95acoopeb30ans6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.seattleInfoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2YM_uP8u8D9BiWVQY8k7xq-7pqj6224k',
    appId: '1:1060028705881:web:49fae14afa479cc5eed548',
    messagingSenderId: '1060028705881',
    projectId: 'seattle-info',
    authDomain: 'seattle-info.firebaseapp.com',
    storageBucket: 'seattle-info.firebasestorage.app',
    measurementId: 'G-G1EC0675K4',
  );
}
